version: "3.8"

services:
  cartservice:
    image: thuanlp/online_boutique_cartservice:latest
    container_name: cartservice
    ports:
      - "7070:7070"
    environment:
      - PORT=7070
      - REDIS_ADDR=redis-cart:6379
    resources:
      limits:
        memory: 128Mi
        cpus: "0.3"
      requests:
        memory: 64Mi
        cpus: "0.2"
    healthcheck:
      test: ["CMD", "/bin/grpc_health_probe", "-addr=:7070", "-rpc-timeout=5s"]
      interval: 15s
      retries: 3
      start_period: 20s
      timeout: 5s
    networks:
      - online_boutique_network

networks:
  online_boutique_network:
    driver: bridge
