version: "3.8"

services:
  currencyservice:
    image: thuanlp/online_boutique_currencyservice:latest
    container_name: currencyservice
    environment:
      - PORT=7000
      - DISABLE_PROFILER=1
    ports:
      - "7000:7000"
    healthcheck:
      test: ["CMD", "/bin/grpc_health_probe", "-addr=:7000"]
      interval: 10s
      retries: 3
      start_period: 20s
      timeout: 5s
    resources:
      limits:
        memory: 128Mi
        cpus: "0.2"
      requests:
        memory: 64Mi
        cpus: "0.1"
    networks:
      - online_boutique_network

networks:
  online_boutique_network:
    driver: bridge
