apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /data/redis
    server: 192.168.224.126
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-storage