apiVersion: v1
kind: Service
metadata:
  name: redis-cart
  namespace: online-boutique
spec:
  clusterIP: None 
  selector:
    app: redis-cart
  ports:
  - name: tcp-redis
    port: 6379
    targetPort: 6379
