apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: frontend-cert
  namespace: shopping-app
spec:
  issuerRef:
    name: selfsigned-cluster-issuer
    kind: ClusterIssuer
  secretName: frontend-cert-secret
  dnsNames:
  - online-boutique.lptdevops.website
